### ISSUE TITLE
[REFACTOR] Fix Template Issues Pt. II

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#133]
**Top Bar**
- [x] Fix Chevron Size

**Course Views**
- [x] On Mobile, make the sub-menu have a floating chevron to indicate you can scroll
- [x] labview -> lablist
- [x] mainview -> course_dashboard
- [x] gradeview -> gradelist
- [x] ~~Create LabView~~

**Dashboard**
- [x]  Remove "Foo" and "Bar" Fields
- [x]  Pull Course and Labs View from Database
- [x] Complain Button :(
- [x] Dashboard Colors : (

**Explore**
- [x] Course Number and Instructor Needn't be labeled, or put in the weird order they are.
- [x] Link from Explore View to Course
- [x] Link from Search View to Course
- [ ] Fix Instructor ID / Name Schema
- [x] Change "Course Page" button to "Enroll" and correct link

**Task View**
- [x] Display List of Task Names and Progress
- [x] Allow Users to return to prior tasks
- [x] Make return to course button contextually more clear
- [x] Make the task view a left off-canvas on mobile

**Comment by sandershihacker** [comment]
Top Bar, Course Views, Dashboard completed.

**Comment by sandershihacker** [comment]
Explore page content order completed, link from explore view and search view to course dashboard completed.

**Comment by sandershihacker** [comment]
Display list of task names in sidenav complete.

**Comment by DerekTBrown** [comment]
Last remaining issue moved to https://github.com/learnlinux/tuxlab-app/issues/161
